# Generated by Django 3.2.16 on 2022-12-07 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinglistitem',
            name='due_date',
        ),
        migrations.AddField(
            model_name='bookinglistitem',
            name='showsdatetime',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
